### PR TITLE
Auto distribute callback names by timestamp :)

### PR DESCRIPTION
**Pull request by Dafrok**
The parameter `callback` is not the same as described in the comment, it's not `Function` type.

### CODE REVIEW

**Comment by cferdinandi** [comment]
In keeping with how jQuery handles JSONP, and for weight/simplicity reasons, I would prefer to not pass in a callback function but rather just reference it.

Thanks for this, though. Cool way to do things I wasn't aware of.

**Comment by Dafrok** [comment]
Anyway your package helps me a lot, thanks.

**Comment by Dafrok** [comment]
By the way, the comment `@param  {Function} callback The function to run after JSONP data loaded`, that 'Function' should be 'String' instead.

**Comment by cferdinandi** [comment]
You're 100% right. I'll update that soon!

**Pull request closed without merging**
